package Libre;

import Joption.Joption;
import Joption.Joptionx;
import Terceros.Usuario;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;


public class Login extends javax.swing.JFrame implements Runnable{

  Joption icon = new Joption();
  Joptionx save = new Joptionx(); 
  String hora, minutos, segundos;
  Thread hilos;
  public static String Usu="",Con="";

  Conexion con;
  void cancelar(){
        TxtUsuario.setText("");
        TxtCon.setText("");
    }
  
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        TxtUsuario.requestFocus(true);
        Ldate.setText(Fecha());
        hilos = new Thread(this);
        hilos.start();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ingreso de Accesso de Usuarios");
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icon monitor pc.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("imagenes/wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }     
    
    public void Limpiar()
    {
        TxtUsuario.setText("");
        TxtCon.setText("");
        TxtUsuario.requestFocus(true);
        TxtUsuario.setBackground(Color.YELLOW);
        TxtCon.setBackground(Color.YELLOW);          
    }
    
    public void Iniciar()
    {
         con = new Conexion();
         Connection reg = con.getConnection();
         String AcoUsu ="0", ConUsu="0";
         ResultSet st;
         Statement cn;
        try
         {
         cn = reg.createStatement();
         st =cn.executeQuery("SELECT * FROM  `usuarios`  WHERE  `Usuario`='"+TxtUsuario.getText()+"' AND  `Clave`='"+TxtCon.getText()+"'");
         do {
              if(st.next()){
              AcoUsu = st.getString("Usuario");
              ConUsu = st.getString("Clave");
              
              if(AcoUsu.equals(TxtUsuario.getText()) && ConUsu.equals(TxtCon.getText()))
              {
                  this.dispose();
                  Usu=TxtUsuario.getText();
                  Con=TxtCon.getText();
                  Libre.Menu windows =new  Libre.Menu();
                  windows.setVisible(true);
                  windows.setLocationRelativeTo(null);
                  this.dispose();                 
            }
           }else
              {
                  JOptionPane.showMessageDialog(null, "Usuario o Contraseña inconrerta ","ERROR",JOptionPane.ERROR_MESSAGE,save);
                  Limpiar();
              }
         } while(st.next());
         }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Error"+ex );
         }
    }
    
    public void Desconetar()
    {
       con.desconectar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        TxtCon = new javax.swing.JPasswordField();
        BtIngresar = new javax.swing.JButton();
        BtSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ldate = new javax.swing.JLabel();
        lhora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        reg = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/Lap.png"))); // NOI18N

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        TxtCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConActionPerformed(evt);
            }
        });

        BtIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/entrar.png"))); // NOI18N
        BtIngresar.setText("Ingresar");
        BtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIngresarActionPerformed(evt);
            }
        });

        BtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/cancelar.png"))); // NOI18N
        BtSalir.setText("Cancelar");
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO : ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA :");

        Ldate.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        Ldate.setForeground(new java.awt.Color(255, 255, 255));
        Ldate.setText("dd/mm/yyyy");

        lhora.setBackground(new java.awt.Color(255, 255, 0));
        lhora.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        lhora.setForeground(new java.awt.Color(255, 255, 255));
        lhora.setText("00:00:00");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(0, 0, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/admin.png"))); // NOI18N
        jMenu1.setText("ADMINISTRADOR");
        jMenu1.setFocusPainted(true);
        jMenu1.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N

        reg.setBackground(new java.awt.Color(51, 51, 255));
        reg.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/icon monitor pc.png"))); // NOI18N
        reg.setText("Nuevo Registro");
        reg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jMenu1.add(reg);

        jMenuItem2.setBackground(new java.awt.Color(51, 51, 255));
        jMenuItem2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libre/imagenes/salir.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Ldate)
                        .addGap(50, 50, 50)
                        .addComponent(lhora)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(BtIngresar)
                                .addGap(33, 33, 33)
                                .addComponent(BtSalir)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCon)
                                    .addComponent(TxtUsuario))
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ldate)
                    .addComponent(lhora))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtIngresar)
                    .addComponent(BtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
      
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void BtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIngresarActionPerformed
        if(TxtUsuario.getText().equals("")){
        JOptionPane.showMessageDialog(null, "El campo de usuario esta vacio","ERROR",JOptionPane.ERROR_MESSAGE,save);
        TxtUsuario.requestFocus(true);
        TxtUsuario.setBackground(Color.YELLOW);
        return;
        }
        else{
            TxtUsuario.setBackground(Color.WHITE);
        }
        if(TxtCon.getText().equals("")){
        JOptionPane.showMessageDialog(null, "El campo de Contraseña esta vacio","ERROR",JOptionPane.ERROR_MESSAGE,save);
        TxtCon.requestFocus(true);
        TxtCon.setBackground(Color.YELLOW);
        return;
        }
         else {
            TxtCon.setBackground(Color.WHITE);
        }  
        Iniciar();
    }//GEN-LAST:event_BtIngresarActionPerformed
    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
       cancelar();
    }//GEN-LAST:event_BtSalirActionPerformed

    private void TxtConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConActionPerformed
      
    }//GEN-LAST:event_TxtConActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        Usuario re= new Usuario();
        re.setVisible(true);
        reg.setVisible(false);
    }//GEN-LAST:event_regActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(null,"Sistema Finalizado","",JOptionPane.INFORMATION_MESSAGE,icon);
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String Fecha(){
    Date fecha = new Date();
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd/mm/yyyy");
    return formatofecha.format(fecha);
    }
    public void Hora(){
    Calendar caledario = new GregorianCalendar();
    Date horaactual = new Date();
    caledario.setTime(horaactual);
    hora= caledario.get(Calendar.HOUR_OF_DAY)>9?""+caledario.get(Calendar.HOUR_OF_DAY):"0"+caledario.get(Calendar.HOUR_OF_DAY);
    minutos= caledario.get(Calendar.MINUTE)>9?""+caledario.get(Calendar.MINUTE):"0"+caledario.get(Calendar.MINUTE);
    segundos= caledario.get(Calendar.SECOND)>9?""+caledario.get(Calendar.SECOND):"0"+caledario.get(Calendar.SECOND);
    }
    
    public void run(){
     Thread current=Thread.currentThread();
     while(current==hilos){
    Hora();
     lhora.setText(hora+":"+minutos+":"+segundos);     
     }
    }   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Login().setVisible(true);        
            }
        });
    }

   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtIngresar;
    private javax.swing.JButton BtSalir;
    private javax.swing.JLabel Ldate;
    private javax.swing.JPasswordField TxtCon;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lhora;
    private javax.swing.JMenuItem reg;
    // End of variables declaration//GEN-END:variables
}
